sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - master
    - develop

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpunit --testsuite system

after_success:
  - bash <(curl -s https://codecov.io/bash)
